In [1]:
from sklearn.datasets import load_iris
from sklearn import tree
%matplotlib inline
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np

# 创建数据实例iris
iris = load_iris()
# 创建模型实例clf
clf = tree.DecisionTreeClassifier()
# 使用clf的fit方法
clf = clf.fit(iris.data, iris.target)




In [2]:


# data1 = pd.DataFrame(load_iris,columns = ['1','2','3','4','5'])
# sns.pairplot(data = data1, hue = '5')

In [3]:
iris.data[::-15]  # 查看前5个样本的数据，每个样本有4个featrues

array([[5.9, 3. , 5.1, 1.8],
       [6.1, 2.6, 5.6, 1.4],
       [6. , 2.2, 5. , 1.5],
       [6.5, 3. , 5.8, 2.2],
       [5.5, 2.5, 4. , 1.3],
       [6.4, 2.9, 4.3, 1.3],
       [5.2, 2.7, 3.9, 1.4],
       [5.1, 3.8, 1.9, 0.4],
       [4.7, 3.2, 1.6, 0.2],
       [5.8, 4. , 1.2, 0.2]])

In [4]:
iris.target[::-15]   # 一共有三类，分别用0，1，2数字来表示

array([2, 2, 2, 2, 1, 1, 1, 0, 0, 0])

In [5]:
"""
预测数据的标准格式，取第一个元素的全部特征值[  [f1,f2,f3,f4], ]
注意predict函数接收的应该是一个含有样本的列表，而每个样本含有4个内容features
"""
iris.data[:1,:]

array([[5.1, 3.5, 1.4, 0.2]])

In [6]:
iris.data[:1]  # 取第一个数据的所有内容也是一样的

array([[5.1, 3.5, 1.4, 0.2]])

In [7]:
"""
注意如果这样西写的话提出来的是个元素，也就是一个含有4个元素的列表，
这样会报错，因为你给了四个样本,
每个样本都只有一个feature
"""
iris.data[0]  

array([5.1, 3.5, 1.4, 0.2])

In [8]:
clf.predict(iris.data[:1]) # 说明属于target中的第一类

array([0])

In [9]:
clf.predict([[.3, 3.9 , 1000.5, 100]])

array([2])

In [10]:
import graphviz # doctest: +SKIP
dot_data = tree.export_graphviz(clf, out_file=None) # doctest: +SKIP
graph = graphviz.Source(dot_data) # doctest: +SKIP
graph.render("iris123") # doctest: +SKIP

'iris123.pdf'